name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build WAR
      run: |
        mkdir -p build/classes
        mkdir -p war_build
        jar cvf Instasmart.war -C build/classes . -C src/main/webapp .
    - name: Archive WAR
      uses: actions/upload-artifact@v3
      with:
        name: Instasmart-war
        path: Instasmart.war
